apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testpod1
  name: testpod1
  namespace: app-a
spec:
  containers:
  - args:
    - curl
    - http://front-service:8080/customerDetails/1
    image: radial/busyboxplus:curl
    name: testpod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
