---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      featureGates:
        KubeletTracing: true
      tracing:
        samplingRatePerMillion: 100
  - role: worker
featureGates:
  APIServerTracing: true
  KubeletTracing: true
