apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-remote-service
  namespace: observability
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "<api-key>"
          "x-honeycomb-dataset": "k8-Trace-Date"
      logging:
      jaeger:
        endpoint: "jaeger-collector.observability.svc:14250"   
        tls:
          insecure: true  
      zipkin:
        endpoint: "http://zipkin.observability.svc:9411/api/v2/spans"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging,jaeger,zipkin]
