apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-deployment
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
      jaeger:
        endpoint: "jaeger-collector.default.svc.cluster.local:14250"   
        tls:
          insecure: true   
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging,jaeger]
